services:
  db:
    image: postgres:18
    container_name: ecommwebapp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_site_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_site_2"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommercewebapp
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_site_2}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd123
    ports:
      - "8084:8080"

volumes:
  pgdata:
