spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_site_2
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate   
spring.jpa.show-sql=True               

# Thymeleaf Configuration
spring.thymeleaf.cache=false